[package]
name = "scz"
version = "0.1.0"
edition = "2024"

[dependencies]
# Logic
chrono = { version = "0.4", features = ["alloc"] }
glam = "0.29" # Matching your use of Vec2
num = "0.4"

# Rendering & Windowing
winit = "0.29"
vello = { version = "0.3.0", features = ["wgpu"] }
egui = "0.27"

# Spatial
geo-types = "0.7"
pollster = "0.4.0"

skrifa = "0.22" # Latest for 2026
swiss-eph = { version = "0.2", features = ["embedded-ephe"] }
